POST http://localhost:3000/create
Content-Type: application/json

{
    "firstname": "",
    "lastname": "",
    "useraddress": "",
    "status" :true
}

###

PUT http://localhost:3000/update
Content-Type: application/json

{
    "_id": "",
    "firstname": "",
    "lastname": "",
    "useraddress": "",
    "status" :true
}

###

DELETE http://localhost:3000/delete
Content-Type: application/json

{
    "_id": ""
}

###

GET http://localhost:3000/display